name: Build and create ZIP
run-name: Generate javascript, ui and schema to publish
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt -q update
          sudo apt -q install --no-install-recommends npm
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup environment
        run: |
          ${{github.workspace}}/build.sh setup_env
      - name: Check TypeScript
        run: |
          ${{github.workspace}}/build.sh check
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt -q update
          sudo apt -q install --no-install-recommends npm blueprint-compiler libglib2.0-0 bash gnome-shell libgtk-4-bin libgtk-4-common libgtk-4-dev libadwaita-1-dev gir1.2-adw-1 gir1.2-gtk-4.0
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Ubuntu specific workarounds
        run: |
          sudo rm /usr/lib/x86_64-linux-gnu/girepository-1.0/Adw-1.typelib
          sudo rm -r /usr/include/libadwaita-1
          sudo rm /usr/lib/x86_64-linux-gnu/libadwaita-1.so
          sudo rm /usr/share/gir-1.0/Adw-1.gir
          sudo rm /usr/lib/x86_64-linux-gnu/pkgconfig/libadwaita-1.pc
          sudo mv ${{github.workspace}}/.github/workflows/ubuntu/Adw-1.typelib /usr/lib/x86_64-linux-gnu/girepository-1.0/
          sudo mv ${{github.workspace}}/.github/workflows/ubuntu/libadwaita-1 /usr/include/
          sudo mv ${{github.workspace}}/.github/workflows/ubuntu/libadwaita-1.so.0 /usr/lib/x86_64-linux-gnu/
          sudo mv ${{github.workspace}}/.github/workflows/ubuntu/libadwaita-1.pc /usr/lib/x86_64-linux-gnu/pkgconfig/libadwaita-1.pc
          sudo mv ${{github.workspace}}/.github/workflows/ubuntu/Adw-1.gir /usr/share/gir-1.0/Adw-1.gir
      - run: ${{github.workspace}}/build.sh setup_env
      - run: ${{github.workspace}}/build.sh build
      - run: ${{github.workspace}}/build.sh format
      - run: ${{github.workspace}}/build.sh copy_static
      - uses: actions/upload-artifact@v3
        with:
          name: randomwallpaper@iflow.space.shell-extension.zip
          path: ${{github.workspace}}/randomwallpaper@iflow.space
