name: Build and create ZIP
run-name: Generate javascript, ui and schema to publish
on: [push, pull_request]
jobs:
  check-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: sibiraj-s/action-eslint@v2
        with:
          extensions: 'ts'
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Install dependencies
      run: |
        sudo apt -q update
        sudo apt -q install --no-install-recommends npm blueprint-compiler zip libglib2.0-0 bash gnome-shell libgtk-4-bin libgtk-4-common libgtk-4-dev libadwaita-1-0 libadwaita-1-dev
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Ubuntu specific workarounds
      run: |
        npm install -g npm@latest typescript@latest eslint@latest
        export PATH=$PATH:$(npm bin -g)
        sed -i -E 's#(blueprint-compiler .*)#\1 || true#g' ${{github.workspace}}/build.sh
    - name: Run build script
      run: /usr/bin/env bash ${{github.workspace}}/build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: randomwallpaper@iflow.space.shell-extension.zip
        path: ${{github.workspace}}/randomwallpaper@iflow.space
